name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: check Go version
      run: go version
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./internal/... ./internal/...
    
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
